# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  wpindi.com:
    site_hosts:
      - canonical: wpindi.com
        redirects:
          - www.wpindi.com
    local_path: ../wpindi.com # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:wpindi/azure-1.git # replace with your Git repo URL
    repo_subtree_path: wpindi.com # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  jtrans.web.id:
    site_hosts:
      - canonical: jtrans.web.id
        redirects:
          - www.jtrans.web.id
    local_path: ../jtrans.web.id # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:wpindi/azure-1.git # replace with your Git repo URL
    repo_subtree_path: jtrans.web.id # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  mywaynews.id:
    site_hosts:
      - canonical: mywaynews.id
        redirects:
          - www.mywaynews.id
    local_path: ../mywaynews.id # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:wpindi/azure-1.git # replace with your Git repo URL
    repo_subtree_path: mywaynews.id # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
